// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package httpcache

import (
	"database/sql"
)

type Response struct {
	ReqHash    string
	Body       sql.NullString
	Headers    sql.NullString
	StatusCode sql.NullInt64
	UpdatedAt  sql.NullString
}
