// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlite

import (
	"context"
	"database/sql"
)

const cacheResponse = `-- name: CacheResponse :one
INSERT INTO responses (
  req_hash, body, headers, status_code
)
VALUES (
  ?, ?, ?, ?
)
RETURNING req_hash, body, headers, status_code, updated_at
`

type CacheResponseParams struct {
	ReqHash    string
	Body       sql.NullString
	Headers    sql.NullString
	StatusCode sql.NullInt64
}

func (q *Queries) CacheResponse(ctx context.Context, arg CacheResponseParams) (Response, error) {
	row := q.db.QueryRowContext(ctx, cacheResponse,
		arg.ReqHash,
		arg.Body,
		arg.Headers,
		arg.StatusCode,
	)
	var i Response
	err := row.Scan(
		&i.ReqHash,
		&i.Body,
		&i.Headers,
		&i.StatusCode,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllResponses = `-- name: DeleteAllResponses :exec
DELETE FROM responses
`

func (q *Queries) DeleteAllResponses(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllResponses)
	return err
}

const getResponse = `-- name: GetResponse :one
SELECT req_hash, body, headers, status_code, updated_at FROM responses WHERE req_hash = ? LIMIT 1
`

func (q *Queries) GetResponse(ctx context.Context, reqHash string) (Response, error) {
	row := q.db.QueryRowContext(ctx, getResponse, reqHash)
	var i Response
	err := row.Scan(
		&i.ReqHash,
		&i.Body,
		&i.Headers,
		&i.StatusCode,
		&i.UpdatedAt,
	)
	return i, err
}
