// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Response struct {
	ReqHash    string
	Body       pgtype.Text
	Headers    pgtype.Text
	StatusCode pgtype.Int4
	UpdatedAt  pgtype.Timestamptz
}
